heart = ("       ff     ff\r\n"
   "     f   f   f   f\r"
   "\n"
   "    f     f f     f"
   "\r\n"
   "    f      f      f"
   "\r\n"
   "    f             f"
   "\r\n"
   "     f           f\r"
   "\n"
   "      f         f\r"
   "\n"
   "       f       f\r\n"
   "        f     f\r\n"
   "         f   f\r\n"
   "          f f\r\n"
   "           f");

